### ISSUE TITLE
Size of the whole bundle is large - proposal

### ISSUE THREAD

**Issue by msurguy** [zeit-ui/vue-icons#13]
Hi! 

It appears that the whole bundle has lots of repeating code (looking at https://cdn.jsdelivr.net/npm/@zeit-ui/vue-icons@latest/dist/index.umd.min.js).

I think it is because currently the package consists of multiple files that don't share common code: 
- icon 
- icon
- icon

AFAIK the only difference between each icon's Vue component - is the SVG path data while the rest of the code is common between all icons, but it still gets duplicated because they're all separate files...

What if the icon would be made into a component that would take the SVG paths from a set of files that just export SVG paths instead of complete SVG code? 

Like this:
- icon.vue
  - paths (folder)
     - twitter.js
     - facebook.js
     - otherIcon.js

Icon.vue would take in icon name as param and import that icon's path data
Files like twitter.js would only contain array of paths: 

```js
export default ['M22 12h-4l-3 9L9 3l-3 9H2', 'M12 15l5 6H7l5-6z']
```

This is just a proposal. Basically instead of a bunch of files with common code, you'd only end up with single Vue component that can import only the paths. Obviously, it would be a breaking change between previous version, but can significantly reduce the size of the bundle.

Let me know what you think about this!

**Comment by unix** [comment]
Good point.
Unfortunately, not all SVGs are standard. The `stork` and `fill` or other attributes are filled dirrerently, and some SVGs use `circle`:

```jsx
// svg1
<svg stroke="currentColor" fill="var(--geist-fill)"></svg>

// svg2
<svg stroke="var(--geist-stroke)" fill="none"></svg>

// svg3
<svg stroke="var(--geist-stroke)" fill="none">
  <circle cx="12" cy="12" r="10" fill="var(--geist-fill)"></circle>
</svg>
```

If we use abstract text to describe the template of multiple conditions, the volume of their meta information is very close.
But you proposal is very good, there are still a few `attributes` and `scripts` that can be abstracted. I'll try to  optimizing their volume later, when I have a minimum available version, I will create a new PR link to here.

**Comment by unix** [comment]
The icon library of React needs similar optimization: [issue#8](https://github.com/zeit-ui/react-icons/issues/8)

**Comment by unix** [comment]
Version `3.1.0-rc.4` has been released.
[min.js](https://cdn.jsdelivr.net/npm/@zeit-ui/vue-icons@3.1.0-rc.4/dist/index.umd.min.js)
[diff changes](https://cdn.unix.bio/?q=@zeit-ui/vue-icons&npm=1)

**Comment by msurguy** [comment]
Thanks @unix ! This is a big improvement already. Nice job!

Btw, I don't know if you already ran the icons through SVGO, but it looks like it's possible to convert circles to paths (if you want all icons to only have `paths`) and also trim to single decimal instead of two decimals without affecting quality.

**Comment by unix** [comment]
@msurguy 
Brilliant! This repo can make us better, I will  continue to test and improve them.
I will remind you here if we have any new changes in optimization.

**Comment by msurguy** [comment]
@unix I moved the files into `svg-raw` and ran the repo through SVGO CLI tool with this config.yaml in the root of the project:
```yaml
plugins:
  - cleanupNumericValues
  - convertShapeToPath
  - convertEllipseToCircle
  - collapseGroups
  - convertPathData
  - convertTransform

```
`svgo -p 1 -f svgs-raw -o svgs --config=config.yaml`

The size of optimized SVG folder is now 123kb (vs 172kb unoptimized) and they appear to be working the same way as before. Feel free to use that config and maybe put it into your pipeline :)
