### ISSUE TITLE
Icon imports in components throws UNDEFINED in Nuxt 2.13.0

### ISSUE THREAD

**Issue by lambrohan** [zeit-ui/vue-icons#18]
**Error** `[Vue warn]: Property or method "EditIcon" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.`

Here is my component.vue
```
<template>
  <div id="my-component">

    <zi-button
      :icon="EditIcon"
      shadow
      id="fab"
    >
      MyButton
    </zi-button>
 
  </div>
</template>

<script>
import EditIcon from '@zeit-ui/vue-icons/packages/edit'
export default {
  name: 'MyComponent',
  components: { EditIcon },
  data() {
    return {
    }
  },
  mounted() {},
  apollo: {

  },
  methods: {

</script>

<style lang="scss" scopped>
</style>
```

**package.json**
```
{
  "name": "zeit-nuxt",
  "version": "1.0.0",
  "description": "My fantastic Nuxt.js project",
  "author": "-------",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate"
  },
  "dependencies": {
    "@zeit-ui/themes": "^1.0.0",
    "@zeit-ui/vue": "^2.4.0",
    "@zeit-ui/vue-icons": "^3.1.0-rc.3",
    "nuxt": "^2.13.0",
  },
  "devDependencies": {
    "@nuxtjs/style-resources": "^1.0.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-prettier": "^3.1.2",
    "sass-loader": "^8.0.2",
    "node-sass": "^4.14.1",

  }
}
```

**Comment by unix** [comment]
Sorry for the delay. I can't reproduce your issue, but I guess this is due to your `nuxt` config error, we have a working online example for you that might help: [codesandbox](https://codesandbox.io/s/ecstatic-margulis-6y4jq?file=/pages/index.vue).

**Comment by lambrohan** [comment]
Thanks for the reply. I've reproduced the bug here at [codesandbox](https://codesandbox.io/s/admiring-rosalind-pz2kw?file=/pages/index.vue). Also  I'm using the Icon with zi-button as referred in the documentation  [here](https://vue.zeit-ui.co/en-us/button).

**Comment by Lzumikonata** [comment]
The attribute `:icon` require a variable of `this` (Vue instance), not a component, because `:icon="EditIcon"` not a template syntax:

```vue
<zi-button :icon="EditIcon" />
<script>
import EditIcon from '@zeit-ui/vue-icons/packages/edit'

export default {
  data: () => ({
    EditIcon,
  })
}
</script>
```

[Here](https://codesandbox.io/s/jolly-leavitt-u9f28?file=/pages/index.vue) is an online example for Icon with `Button`.

**Comment by Lzumikonata** [comment]
`:icon` is implemented by Dynamic Components.
```
<component v-bind:is="currentTabComponent"></component>

```
The attribute  `:icon` of `Tab` also use it.

**Comment by lambrohan** [comment]
Thanks!
