### ISSUE TITLE
Failed to build when running in universal mode in Nuxt.js

### ISSUE THREAD

**Issue by Creedowl** [zeit-ui/vue-icons#22]
If I run my app in universal mode (with ssr), I will get a build error
Here is a [demo](https://codesandbox.io/s/dawn-lake-5k5xp?file=/nuxt.config.js)
But if I change to spa mode, it works well

**Comment by Lzumikonata** [comment]
I created an online [example](https://codesandbox.io/s/frosty-mayer-gn87g?file=/pages/index.vue) on codesandbox.
If you set the mode to 'universal', the configuration of build should be
```
build: {
  transpile: ['zeit'], // Match [@zeit-ui/vue-icons]
}

```

**Comment by Creedowl** [comment]
Thanks a lot!
