### ISSUE TITLE
webpack打包出错

### ISSUE THREAD

**Issue by pape2016** [zeit-ui/vue-icons#6]
根据https://vue-icons.zeit-ui.co/   上面的步骤
安装了@zeit-ui/themes @zeit-ui/vue-icons
然后引入

import '@zeit-ui/themes/index.css'      // default theme
import '@zeit-ui/themes/dark.css'       // dark theme
import { install } from '@zeit-ui/vue-icons'
import Vue from 'vue'
install(Vue)

然后运行webpack命令打包
出现错误

ERROR in ./node_modules/@zeit-ui/vue-icons/packages/index.js
Module not found: Error: Can't resolve './zoom-out' in 'C:\project\tooltip\node_modules\@zeit-ui\vue-icons\packages'
 @ ./node_modules/@zeit-ui/vue-icons/packages/index.js 355:0-36 715:33-44 725:0-1085:1
 @ ./main.js

然后我在C:\project\tooltip\node_modules\@zeit-ui\vue-icons\packages目录下将heart.vue文件直接复制到我这个测试项目根目录import引入这个组件，可以显示一个心形。

**Comment by unix** [comment]
请补充这些信息：
 - `@zeit-ui/vue-icons` 版本
 - 使用 `zoom-out` 时的引入方式以及模板使用方式
 - 是否使用了 `zeit-ui/vue`

如果可能，最好在 `https://codesandbox.io` 上提供一个示例。有任何更新，请直接 `@` 我。

**Comment by pape2016** [comment]
1. @zeit-ui/vue-icons版本是3.0.0，依赖如下：
"devDependencies": {
    "@zeit-ui/themes": "^1.0.0",
    "@zeit-ui/vue": "^2.4.0",
    "@zeit-ui/vue-icons": "^3.0.0",
    "css-loader": "^3.5.3",
    "html-webpack-plugin": "^3.2.0",
    "vue": "^2.6.11",
    "vue-loader": "^15.9.1",
    "vue-style-loader": "^4.1.2",
    "vue-template-compiler": "^2.6.11",
    "webpack": "^4.43.0"
  }

2. 不只是提示zoom-out，从activity开始所有的图标都提示了一遍：
ERROR in ./node_modules/@zeit-ui/vue-icons/packages/index.js
Module not found: Error: Can't resolve './activity' in 'C:\project\zeit-ui-icons\node_modules\@zeit-ui\vue-icons\packages'
 @ ./node_modules/@zeit-ui/vue-icons/packages/index.js 1:0-37 361:33-45 725:0-1085:1
 @ ./main.js

ERROR in ./node_modules/@zeit-ui/vue-icons/packages/index.js
Module not found: Error: Can't resolve './add-team' in 'C:\project\zeit-ui-icons\node_modules\@zeit-ui\vue-icons\packages'
 @ ./node_modules/@zeit-ui/vue-icons/packages/index.js 2:0-36 362:33-44 725:0-1085:1
 @ ./main.js

ERROR in ./node_modules/@zeit-ui/vue-icons/packages/index.js
Module not found: Error: Can't resolve './airplay' in 'C:\project\zeit-ui-icons\node_modules\@zeit-ui\vue-icons\packages'
 @ ./node_modules/@zeit-ui/vue-icons/packages/index.js 3:0-35 363:32-43 725:0-1085:1
 @ ./main.js
......
很长的错误。

3.先试了一下不用@zeit-ui/vue，后试了一下使用 @zeit-ui/vue，报一样的错误。

4. sandbox不知道为什么巨慢无比，我把demo项目放到github了，clone下来之后，npm install， 然后webpack就会出现上述错误信息。
https://github.com/pape2016/zeit-ui-icons.git

@unix

**Comment by pape2016** [comment]
找到原因了。
index.js里面引入的时候没有写组件后缀.vue
import activityIcon from './activity'
改为
import activityIcon from './activity.vue'
就可以了。
我将这里的引入全部加上了.vue后缀名，然后webpack命令打包成共，页面显示了心形。

**Comment by unix** [comment]
OK。
你可以在 `resolve.extensions` 里面加上 `.vue`，应该可以自动忽略后缀。
`webpack` 的文档在[这里](https://www.webpackjs.com/configuration/resolve/#resolve-extensions)，示例：

```js
{
  extensions: [".js", ".vue"],
}
```

**Comment by pape2016** [comment]
我刚研究出来。。。加上了。
非常感谢。我可以用zeit-ui的图标了，撒花。
