### ISSUE TITLE
设置图标大小颜色和空心实心

### ISSUE THREAD

**Issue by pape2016** [zeit-ui/vue-icons#7]
有三个小建议，不知道合不合理，望斟酌。
1. 请问可以增加设置图标大小的属性吗？现在显示在页面上跟旁边的字体和元素大小不匹配，显得太大了，又没有办法缩小。

2. 另外颜色想改成红色的，默认是黑色的。可以在外面包一层div来设置颜色，但是加了一层div之后有时候会引起布局的变化，如果有一个属性可以直接设置颜色会更合理一些。

3. 另外图标一样，但是只有空心和实心区别的图标可以合并为一个吗？然后通过属性来设置是否实心。

谢谢。

**Comment by unix** [comment]
1. 图标本身就是一个 SVG 元素，就使用 CSS 控制 SVG 元素即可，包括颜色和大小。ZEIT Vue 系列的库在使用时都是这样做的。但是还是可以增加大小属性，这个功能可能需要一段时间，完成后我会再提醒你。
2. 颜色也建议用 CSS 设置，但图标库本身也是也可以优化的，也加在上诉 Feature 内。
3. 只有空心和实心目前是分开的，因为如果要一一针对去做这件事实际上需要对所有图标手动更改，更改后也不能再用脚本更新，日后都需要手动维护。如果你想要这样做，完全可以新创建一个 `.vue` 文件，引入 2 个图标然后根据条件判断渲染。实际体验是相同的，但条件判断可能会小一些，但不会太高，总体优化后估计手动维护的 SVG 最多也只能缩小几十 `B`。

**Comment by unix** [comment]
我刚刚发布了一个 pre-relesae 版本提供试用，支持 `size` 和 `color` 两种属性，你可以运行 `npm install @zeit-ui/vue-icons@latest` 安装试用版。

**Comment by pape2016** [comment]
好的，非常感谢！
我更新一下版本。
